### ISSUE TITLE
Update the git clone command

### ISSUE THREAD

**Issue by SebastianKuppa** [OpShin/opshin-example#2]
Hey, after trying to clone the repository, I realized that the git clone links are not up-to-date (still ImperatorLang, instead of opshin).

**Comment by nielstron** [comment]
Thanks for the heads up! The repo is a bit outdated generally since the focus shifted to https://github.com/OpShin/opshin-starter-kit

Will fix it though :)

**Comment by SebastianKuppa** [comment]
Yeah I get that :) thanks for the great work, that you are doing!
